# Name of workflow
name: CICD

# Manual trigger only
on:
  workflow_dispatch:

jobs:

  # Job 1 - Checkout code
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  # Job 2 - Build
  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Build Docker container
        run: echo "Docker container build"

  # Job 3 - Test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test the container
        run: echo "Testing the container"

  # Job 4 - Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy the app
        run: echo "Docker compose deployed the app"
