name: Hello Praveen

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to users
        run: echo "Hello Praveen"

      - name: Say hello to username
        run: echo "Hello $USER"

  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Show versions of Python and Docker
        run: docker --version && python --version

