
name: Hello Praveen
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello tp users
        run: echo "hello praveen"
      - name: say hello to username
        run: echo "hello $USER"

1:
  runs-on: ubuntu-latest
  steps:
    - name: show what is the version python,docker etc
      run: docker --version && python --version
  
        

